### ISSUE TITLE
Carrying Hyper-parameter Optimization without Server

### ISSUE THREAD

**Issue by ssakhavi** [Element-Research/hypero#4]
Hi Nicholas, 

Is it needed to use a server/client in order to use hypero. I don't understand why I'm going through all the installation details you have provided.

**Comment by nicholas-leonard** [comment]
@ssakhavi Yes you need to set up the server and client. You do not need two computers though. The client-server architecture allows you to run multiple clients on different machines and centralize the results into a single server.
